openapi: 3.0.1
info:
  title: cvgateway
  description: API Definition of cvgateway
  version: 1.0.0
servers:
- url: http://localhost:8290/cvgateway
paths:
  /jobs/{job_id}/applications:
    get:
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      - name: job_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /jobs:
    post:
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      - name: title
        in: query
        schema:
          type: string
      - name: company
        in: query
        schema:
          type: string
      - name: description
        in: query
        schema:
          type: string
      - name: required_skills
        in: query
        schema:
          type: string
      - name: posting_date
        in: query
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /users:
    get:
      parameters:
      - name: admin_email
        in: query
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
  /users/{user_id}/approve:
    put:
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /users/{user_id}:
    get:
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /jobs/{user_id}/apply:
    post:
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /jobs/{job_id}:
    delete:
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      - name: job_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /applications/{application_id}/{action}:
    put:
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      - name: application_id
        in: path
        required: true
        schema:
          type: string
      - name: action
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /users/{user_id}/role:
    put:
      parameters:
      - name: admin_email
        in: query
        schema:
          type: string
      - name: role
        in: query
        schema:
          type: string
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /applications:
    get:
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
  /jobs/{job_id}/approve:
    put:
      parameters:
      - name: admin_email
        in: query
        schema:
          type: string
      - name: job_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /active/users:
    put:
      parameters:
      - name: email
        in: query
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
